[tool.poetry]
name = "sd"
version = "0.1.0"
description = ""
authors = ["Shanyou Li <shanyouli6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
typer = ">=0.9.0,<=0.11.1"

[tool.poetry.scripts]
sd = "sd.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
